<style>
    a:link,
    a:visited
    {
        color: white;
    }

    span#nerdery-name
    {
        color: #AEC0AF;
        text-shadow: white 1px 1px;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://www.nerdery.com/images/bg_bodynew.jpg);
        width:  600px;
        height: 350px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
        font-family: Helvetica,Arial,sans-serif
    }

    div#more-information
    {
        height: 100%;
    }

    h1
    {
        color: black;
        text-shadow: #D3D9D8 1px 1px;
    }

</style>
<div id="welcome">
    <h1>Welcome to<br/> <span id="nerdery-name">Nerdery</span> <span id="zf-name">Zend Framework!</span></h1>

    <h3>This is your project's main page</h3>

    <div id="more-information">
        <p><img src="http://framework.zend.com/images/PoweredBy_ZF_4LightBG.png" /></p>
        <p><img src="http://codecat.sierrabravo.net/img/logo_nerdery.png" width="130" /></p>
        <p>
            Helpful Links: <br />
            <a href="http://framework.zend.com/">Zend Framework Website</a> |
            <a href="http://framework.zend.com/manual/en/">Zend Framework Manual</a> |
            <a href="https://trac.sierrabravo.net/BEAR/">Bear Trac</a>
        </p>
    </div>
</div>        